# Generated by Django 5.1.3 on 2024-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(unique=True)),
                ('amount', models.FloatField()),
                ('time', models.FloatField()),
                ('location', models.IntegerField()),
            ],
        ),
    ]
